//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectorX.WebserviceX {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebserviceX.IServiceX")]
    public interface IServiceX {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceX/GetData", ReplyAction="http://tempuri.org/IServiceX/GetDataResponse")]
        DomainModel.Customer GetData(string value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceXChannel : ConnectorX.WebserviceX.IServiceX, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceXClient : System.ServiceModel.ClientBase<ConnectorX.WebserviceX.IServiceX>, ConnectorX.WebserviceX.IServiceX {
        
        public ServiceXClient() {
        }
        
        public ServiceXClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceXClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceXClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceXClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DomainModel.Customer GetData(string value) {
            return base.Channel.GetData(value);
        }
    }
}
